### ISSUE TITLE
Spoken text in the event of an alarm

### ISSUE THREAD

**Issue by Beejeedeb** [tim-hellhake/google-home-adapter#1]
Hi Tim,

I would like to use this add-on to generate an alarm when my smoke, gas or water alarm goes off.

I have three scenarios in mind:

1) Smoke alarm:
There is smoke, z-wave smoke sensor is activated, all lights are switched on, the Google home gives an alarm in spoken text.

2) Water or gas alarm:
A leak is detected, all electrical equipment is turned off in the room where the leakage is detected, gas or water is automatically shut off, the Google Home gives an alarm in spoken text.

3) No alarm but a normal announcement:
In addition to an alarm, a normal annoucement is also possible.

I would like to use your add-on for a spoken alarm message. For this, the following should be implemented.

1) Volume of the Google home device can be adjusted (eg to 90%.).
2) The language should be able to be set (eg nl = dutch, de=German)
3) It must be possible to repeat the text (loop).
4) When the messages are over, please switch back to the app that was active before. Now it gets stuck for a long time on the media app.
5) When the messages are over, restore the volume to its original value.

I don't know if it's possible but it could be a nice addition to an alarm. I am not a programmer but please let me know if I can help somehow.

**Comment by Beejeedeb** [comment]
please let me know if I can test something for you.

**Comment by tim-hellhake** [comment]
> The language should be able to be set (eg nl = dutch, de=German)

It's now possible to set the language of a message but I guess it would be handy to have a default language.

**Comment by tim-hellhake** [comment]
> When the messages are over, please switch back to the app that was active before. Now it gets stuck for a long time on the media app.

I'm now closing the default player after the playback is finished.
However, I'm not sure if it's possible to bring back the app which ran before.
It seems to be closed when the default player is launched.

**Comment by Beejeedeb** [comment]
> > The language should be able to be set (eg nl = dutch, de=German)
> 
> It's now possible to set the language of a message but I guess it would be handy to have a default language.

English should be the default language imo.  Google Home works best in English.

**Comment by Beejeedeb** [comment]
> > When the messages are over, please switch back to the app that was active before. Now it gets stuck for a long time on the media app.
> 
> I'm now closing the default player after the playback is finished.
> However, I'm not sure if it's possible to bring back the app which ran before.
> It seems to be closed when the default player is launched.

My Google Home automatically switches back to the Backdrop app when an app is closed and it cant open the app which ran before.

**Comment by Beejeedeb** [comment]
Hi Tim, when will you publish your changes? I am very excited to test the things you added 😊

**Comment by Beejeedeb** [comment]
Awesome! Everything you implemented works. Volume is temporarily increased to 50% and then returns to the original value. Works perfectly for me, maybe confusing for users if they don't know this. I am very happy with this and have given already all my alarms and actions a voice :-)

I wanted to loop the text with a **while** function. However, I cannot select **while** only **if** is possible in the rule.

![while in rule](https://user-images.githubusercontent.com/51539492/61244095-b0130b00-a749-11e9-8bf3-92669451bce1.PNG)

Maybe if you have the time and you don't have enough of this add-on, then consider implementing the following.
I see that in the Chromecast add-on a volume property bubble is used. This allows the sound to be set manually and you can also use it in a rule. This prevents confusion among users that the volume is set to 50% in the background.

![chromecast add on](https://user-images.githubusercontent.com/51539492/61244235-0aac6700-a74a-11e9-9437-32da2c957cd6.PNG)

**Comment by tim-hellhake** [comment]
Good point!
I already thought about adding a config option for the volume to the config but that's definitely better.
Can you test it locally or should i prepare a new release?

**Comment by tim-hellhake** [comment]
Good point!
I already thought about adding a config option for the volume but that's definitely better.
I added a volume parameter to the speak action.
You can set the volume in the preconfigured messages too.
Can you test it locally or should i prepare a new release?

**Comment by Beejeedeb** [comment]
Not sure how to get it on my Pi, it's not copy paste but there is some compiling going on to textscript? New release is for me the easiest.

**Comment by tim-hellhake** [comment]
Release is out: https://github.com/tim-hellhake/google-home-adapter/releases
You have to download and extract the archive manually though.

**Comment by Beejeedeb** [comment]
Hi Tim, The slider in the configuration menu is easier than a slider in a property bubble in the thing. Turning volume on per message works very well. You set the volume and it is put back to the original volume after the message has been delivered. But a slider in a property bubble and a value in the rules is more according to the Mozilla webthings "standard".
However, after deleting (the old pre 0.3.0 messages) and writing a new message, the slider no longer works. No matter what you set, the spoken text will be played at 100%. If I set the slider to 0% then the spoken text is played at 50%.

![volume slider](https://user-images.githubusercontent.com/51539492/61286044-53a00200-a7c2-11e9-8dbe-94d26ccc5e06.PNG)

**Comment by tim-hellhake** [comment]
I think I found the bug.
A new release is available.
Could you please test if it works now?

**Comment by Beejeedeb** [comment]
Success!! It works. You found the bug. The only thing I don't get working yet is repeating the text with the while option. While option isn't selectable. Not sure if that is even possible?

Rule:
**While** zw-smoke-alarm is on, do TTS action "Fire, leave the building"

**Comment by tim-hellhake** [comment]
>The only thing I don't get working yet is repeating the text with the while option

I guess the problem that it is an action.
The `while` in the rule engine isn't really a while.
It's more an `as long as` which is meant to be used for properties.

I see two options here:

* Implement the repeat logic in the action. However, I'm not sure what is the best way to stop the action. I could add a `cancel alert` action.
* Add messages as property which can be turned on and off.

I would rather avoid the last one because it is a misuse of properties.
Additionally, there is already an API (https://github.com/mozilla-iot/gateway/issues/1758) on the way which supposed to be used by notification add-ons like this one.

**Comment by tim-hellhake** [comment]
>But a slider in a property bubble and a value in the rules is more according to the Mozilla webthings "standard".

The problem with the property is that it would be a global value but I think you may want to use different volume levels for different messages.
Additionally, the value of a property should not change back to another value on its own.

**Comment by Beejeedeb** [comment]
> > The only thing I don't get working yet is repeating the text with the while option
> 
> I guess the problem that it is an action.
> The `while` in the rule engine isn't really a while.
> It's more an `as long as` which is meant to be used for properties.
> 
> I see two options here:
> 
> * Implement the repeat logic in the action. However, I'm not sure what is the best way to stop the action. I could add a `cancel alert` action.
> * Add messages as property which can be turned on and off.
> 
> I would rather avoid the last one because it is a misuse of properties.
> Additionally, there is already an API ([mozilla-iot/gateway#1758](https://github.com/mozilla-iot/gateway/issues/1758)) on the way which supposed to be used by notification add-ons like this one.

its probably best to wait for the new notification api.  99% of the desired results have been achieved.

**Comment by Beejeedeb** [comment]
> > But a slider in a property bubble and a value in the rules is more according to the Mozilla webthings "standard".
> 
> The problem with the property is that it would be a global value but I think you may want to use different volume levels for different messages.
> Additionally, the value of a property should not change back to another value on its own.

you are right, that means that the current solution is the best solution within the possibilities of Webthings.

**Comment by Beejeedeb** [comment]
if I can help you to test something else please let me know.

**Comment by Beejeedeb** [comment]
Version 0.9 is available with the notification api.

**Comment by tim-hellhake** [comment]
I created new issues for the remaining points.
Feel free to create additional issues if I missed something.
