### ISSUE TITLE
Repeat alert messages

### ISSUE THREAD

**Issue by tim-hellhake** [tim-hellhake/google-home-adapter#3]
Follow-up of https://github.com/tim-hellhake/google-home-adapter/issues/1

**Comment by tim-hellhake** [comment]
@Beejeedeb 
I added an interval device to the [timer adapter](https://github.com/tim-hellhake/timer-adapter).
The update will be available soon.
It will emmit an `elapsed` event every `n` seconds.
The interval can be activated/deactivated by its `active` property.
You could use this to create a continuous alarm by connecting the interval to a google home device.
Would this be a sufficient solution?

**Comment by Beejeedeb** [comment]
perfect workaround

**Comment by Beejeedeb** [comment]
its not super intuitive but it works, I used three rules. One to activate the interval when there is an alarm. one to trigger the google spoken message and one to deactivate the interval when the alarm is gone. Or can it be done with less rules?

**Comment by tim-hellhake** [comment]
Thanks for asking these important questions.
The longer I think, the more superfluous the `active` property becomes for me.
You can simply combine the interval timer and your alarm condition with an `and` operator.
I think I'll remove it before it leads to overcomplicated rules.

![image](https://user-images.githubusercontent.com/17127122/65837567-337bdb80-e2f9-11e9-9013-0a6391ad5bbd.png)

**Comment by tim-hellhake** [comment]
@Beejeedeb

**Comment by Beejeedeb** [comment]
this is Indeed a much simpler rule, forgot that also the AND operator can be used.

**Comment by tim-hellhake** [comment]
The advantage of this approach is it's reusable.
You can use the interval timer with every addon which has some sort of alert action.
I'm closing the issue now.
Please let me know if you have any ideas for improvement.
