### ISSUE TITLE
cast-start "chime" sound -- is it avoidable?

### ISSUE THREAD

**Issue by kgiori** [tim-hellhake/google-home-adapter#4]
I find the cast-start chime sound annoying and apparently I'm not the only one. I found this link from a search:
https://community.home-assistant.io/t/i-did-it-i-defeated-the-horrible-google-home-cast-start-prompt-sound/36123

Not sure if it is possible for this add-on to avoid that chime when casting to Google Home devices?

**Comment by tim-hellhake** [comment]
@kgiori
The solution in the link was to play a silent sound file to keep the receiver open.
I played around a little bit and it turns out it's possible to mute the volume before opening the receiver.
Could you please try out if it works for you?

**Comment by tim-hellhake** [comment]
@kgiori
I'm closing this now.
Please submit a new issue if you any problem with the addon.
I'll be happy to fix it.
