### ISSUE TITLE
Remove link for Things does not always work

### ISSUE THREAD

**Issue by igilham** [tim-hellhake/google-home-adapter#6]
I installed the addon and connected my Google Home device. The speak command doesn't work, so I'm trying to remove the Things from my gateway. The remove button also doesn't work.

**Comment by kgiori** [comment]
Did you try reloading/restarting your browser, or rebooting your gateway? If removal still does not work then likely some issue with how the adapter handles removal. I have been able to remove and re-add my Google Home device.

**Comment by tim-hellhake** [comment]
I tested it with version `0.9.2` of the gateway.
The `speak` function as well as removing and adding the google home devices worked as expected.
Could you please attach the logs as described in mozilla-iot/gateway#2133?

**Comment by igilham** [comment]
Rebooting the gateway seems to have fixed it.

There are no useful logs, only some Open ZWave stuff that isn't relevant.
