### ISSUE TITLE
modification suggestion

### ISSUE THREAD

**Issue by SandiaScalpel** [tim-hellhake/google-home-adapter#9]
Hi,

Thank you for your work.

If you look at MozillaIOT Email Sender add-on, they were able to make it so that the associated notification for the Thing used in a rule could be configured (title, messgae, level). Is there any way your google-home adapter can be modified to do the same so custom executions in the rules for different situations can be constructed without having to add activities to the actual add-on?

Also, is it possible to give the end user the ability to rename the "Thing" created by your add-on so the unique ID can be removed from the displayed name?

Thanks again, 

Sean

**Comment by tim-hellhake** [comment]
> Thank you for your work.

Always happy to help :)

> the associated notification for the Thing used in a rule could be configured (title, messgae, level).

This looks like the notification API to me.
It was implemented in https://github.com/tim-hellhake/google-home-adapter/issues/2.
Normally there should be a google home notification icon in the rules view.

> it possible to give the end user the ability to rename the "Thing"

You should be able to rename the thing in the detail view.
This is a gateway feature though.

**Comment by tim-hellhake** [comment]
@SandiaScalpel did you find everything?

**Comment by SandiaScalpel** [comment]
Tim,

I ended up reinstalling everything and it seems to work fine now. Thank you.

Sean
